config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'questions#index'
  resources :comments, only: [:create, :new, :edit, :update, :destroy]
  resources :answers, only: [:create, :new, :edit, :update, :destroy]
  resources :questions
  resources :votes, only:[:create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy
  validates :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates :content, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :user

  def self.already_vote?(user_id, id, method)
    if method == "Question"
      votes = Question.find(id).votes
    else
      votes = Answer.find(id).votes
    end
    if votes.find_by(user_id: user_id) == nil
      false
    else
      true
    end
  end
  
  def self.destroy_vote?(user_id, id, method)
    if method == "Question"
      votes = Question.find(id).votes
    else
      votes = Answer.find(id).votes
    end
    votes.find_by(user_id: user_id).destroy 
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  def edit
    @question = Question.find(params[:question_id])
  end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
    else
      flash[:alert] = "The answer hasn't been created"
    end
    redirect_to question_path(id: params[:answer][:question_id])
  end

  def update
    if @answer.update(answer_params)
    else
      flash[:alert] = "The answer hasn't been edited"
    end
    redirect_to question_path(id: params[:answer][:question_id])
  end
  
  def destroy
    @answer.destroy
    redirect_to question_path(id: params[:question_id])
  end

  private
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:content, :question_id, :id, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :create_ransack_object
  
  def create_ransack_object
      @search = Question.ransack(params[:q])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
    else
      flash[:alert] = "The comment hasn't been created"
    end
    redirect_to question_path(id: params[:question_id])
  end

  def update
    if @comment.update(comment_params)
    else
      flash[:alert] = "The comment hasn't been edited"
    end
    redirect_to question_path(id: params[:question_id])
  end

  def destroy
    @comment.destroy
    redirect_to question_path(id: params[:question_id])
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end
    
    def comment_params
      params.require(:comment).permit(:content, :commentable_id, :commentable_type, :user_id)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :update, :detroy]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_ransack

  def index 
    if params[:q].present?
      @questions = @search.result
    else
      @questions = Question.all
    end
  end

  def show
    @answers = @question.answers
    @comment = Comment.new
    @comments = @question.comments
    @vote = Vote.new
    @votes = @question.votes.count
  end

  def edit
  end
  
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to question_path(id: @question.id)
    else
      flash[:alert] = "The question has not been created, due an error"
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to question_path
    else
      flash[:alert] = "The question has not been edited, due an error"
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  private
  
    def set_question
      @question = Question.find(params[:id])
    end

    def set_ransack
      @search = Question.search(params[:q])
    end

    def question_params
      params.require(:question).permit(:title, :content, :user_id)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    if (user_signed_in?)
      unless (Vote.already_vote?(current_user.id, params[:vote][:votable_id], params[:vote][:votable_type]))
        @vote = Vote.new(vote_params)
        if @vote.save
        else
          flash[:alert] = "The Vote hasn't been saved, due an error"
        end
      else
        Vote.destroy_vote?(current_user.id, params[:vote][:votable_id], params[:vote][:votable_type])
        flash[:notice] = "The Vote has been eliminated"
      end
    else
      flash[:alert] = "You must been logged in order to vote"
    end
    respond_to do |f|
      f.html {redirect_to question_path(id: params[:question_id])}
    end
  end

  private
    def vote_comment
      @vote = Vote.find(params[:id])
    end

    def vote_params
      params.require(:vote).permit(:amount, :votable_id, :votable_type, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/answers/_form.html.erb
<%= form_for(answer) do |f| %>
  <%= hidden_field_tag "answer[question_id]", @question.id %>
  <%= hidden_field_tag "answer[user_id]", current_user.id %>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit 'Answer', class: "btn btn-success" %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">      
      <h1>Editing Answer</h1>

      <%= render 'form', answer: @answer %>

    </div>
  </div>
</div>

app/views/answers/index.html.erb
p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Code</th>
      <th>Votes</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.content %></td>
        <td><%= answer.code %></td>
        <td><%= answer.votes %></td>
        <td><%= answer.question %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <h1>New Answer</h1>

      <%= render 'form', answer: @answer %>

      <%= link_to 'Back', answers_path %>
    </div>
  </div>
</div>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>Code:</strong>
  <%= @answer.code %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @answer.votes %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/layouts/_alerts.html.erb
<div class="alerts text-center">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Flow <b>Overstack</b></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <%= search_form_for(@search, url: questions_path, html: { class: 'navbar-form navbar-left' }) do |f| %>
            <div class="form-group"> <%= f.search_field :title_or_content_cont, class: 'form-control', placeholder: 'Search...' %></div>
            <div class="actions">
              <%= button_tag type: 'submit', class: "glyphicon glyphicon-search" do %>
              <% end %>
            </div>
          <% end %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><b><%= current_user.email.split('@')[0].upcase %></b><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Ask Question',new_question_path %></li>
              <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li> <%= link_to 'Log In', new_user_session_path %> </li>
          <li> <%= link_to 'Sign Up', new_user_registration_path %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowOverstack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  
    <script>
      $(".alert").fadeIn(500).css("opacity","0.85").delay(6000).slideUp(1000);
      $('.alerts').on('click','.alert',function(){ $(this).remove()});
    </script>
  </body>
</html>

app/views/questions/_form.html.erb
<% if question.errors.any? %>
  <div id="errors_explanation">
    <h4><%=pluralize(question.errors.count,"error")%> prohibited this question from being saved </h4>
    <ul>
      <% question.errors.full_messages.each do |message| %>
          <li><%=message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(question) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control"%>
  </div>

  <%= hidden_field_tag "question[user_id]", current_user.id %>
  <div class="actions">
    <%= f.submit 'Save', class:"btn btn-success" %>
    <%= link_to 'Cancel', questions_path, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Editing Question</h1>
      <%= render 'form', question: @question %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="questions">
        <h2 class="text-center">Top Questions</h2>
        <%= link_to 'Ask Question', new_question_path, class:"btn btn-primary" %>
      </div>
      <% @questions.each do |question| %>
      <div class="list-group">
        <div class="list-group-item">
          <div class="metrics">
            <div class="votes">
              <div class="mini-counts">
                <span><%= question.votes.size %></span>
              </div>
              <div>votes</div>
            </div>
            <div class="answers">
              <div class="mini-counts">
                <span><%= question.answers.size %></span>
              </div>
              <div>answers</div>
            </div>
          </div>
          <div class="summary">
            <div data-turbolinks="false">
              <div class="title">
                <%= link_to "#{question.title}", question %>
              </div>
              <div class="info">
                <%= link_to "Asked #{time_ago_in_words(question.created_at)}, #{User.find(question.user_id).email.split('@')[0]}" , question %>
              </div>
            </div>
          </div>
          <% if user_signed_in? && current_user.id == User.find(question.user_id).id  %>
            <div class="icons">
              <h3 class="panel-title-right"><%= link_to "", edit_question_path(question), class: 'fa fa-pencil-square-o' %></h3>
              <h3 class="panel-title-right"><%= link_to '', question_path(question), class: 'fa fa-trash', method: :delete, data: { confirm: 'Are you sure?' }  %></h3>
            </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">New Question</h1>
      <%= render 'form', question: @question %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="question-show">
          <div class="panel-votes">
            <h3>
              <%= form_for(@vote, remote: true) do |f| %>
                <%= hidden_field_tag "vote[amount]", true %>
                <%= hidden_field_tag "vote[votable_id]", @question.id %>
                <%= hidden_field_tag "vote[votable_type]", "Question" %>
                <%= hidden_field_tag "question_id", @question.id %>
                <% if user_signed_in? %>
                  <%= hidden_field_tag "vote[user_id]", current_user.id %>
                <% end %>
                <%= button_tag type: 'submit', class: "fa fa-caret-up",id: "plus-vote" do %>
                <% end %>
              <% end %>
            </h3>
            <% if (user_signed_in? && Vote.already_vote?(current_user.id, @question.id,"Question")) %>
              <h3 class= <%= @question.votes.where(:amount => true).count - @question.votes.where(:amount => false).count >= 0 ? 'success' : 'danger'; %>><%=@question.votes.where(:amount => true).count - @question.votes.where(:amount => false).count %></h3>
            <% else %>
              <h3><%=@question.votes.where(:amount => true).count - @question.votes.where(:amount => false).count %></h3>
            <% end %>
            <h3>
              <%= form_for(@vote, remote: true) do |f| %>
                <%= hidden_field_tag "vote[amount]", false %>
                <%= hidden_field_tag "vote[votable_id]", @question.id %>
                <%= hidden_field_tag "vote[votable_type]", "Question" %>
                <%= hidden_field_tag "question_id", @question.id %>
                <% if user_signed_in? %>
                  <%= hidden_field_tag "vote[user_id]", current_user.id %>
                <% end %>
                <%= button_tag type: 'submit', class: "fa fa-caret-down", id: "minus-vote" do %>
                <% end %>
              <% end %>
            </h3>
          </div>
          <div class="question-panel">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title"><%= @question.title %><i class="" aria-hidden="true"></i></h3>
                <% if user_signed_in? && current_user.id == User.find(@question.user_id).id  %>
                  <h3 class="panel-title-right"><%= link_to "", edit_question_path(@question), class: 'fa fa-pencil-square-o' %></h3>
                  <h3 class="panel-title-right"><%= link_to '', question_path(question_id: @question.id), class: 'fa fa-trash', method: :delete, data: { confirm: 'Are you sure?' }  %></h3>
                <% end %>
              </div>
              <div class="panel-body">
                <p class="question-content"><%= markdown(@question.content) %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="comment_section">
          <% if user_signed_in? %>
            <a class="btn btn-primary" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Add Comment</a>
            <br><br>
            <div class="collapse" id="collapseExample">
              <div class="well">
                <%= form_for(@comment, remote: true) do |f| %>
                  <div class="form-group">
                    <%= f.text_area :content, class:"form-control" %>
                  </div>
                  <%= hidden_field_tag "comment[commentable_id]", @question.id %>
                  <%= hidden_field_tag "comment[commentable_type]", "Question" %>
                  <%= hidden_field_tag "question_id",@question.id %>
                  <%= hidden_field_tag "comment[user_id]", current_user.id %>
                  <div class="actions">
                    <%= f.submit 'Comment', class: "btn btn-success" %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
          <% @comments.each do |comment| %>
            <div class="panel panel-default">
              <div class="comment">
                <p><%= "Commented #{time_ago_in_words(comment.created_at)}, #{User.find(comment.user_id).email.split('@')[0]}" %></p>
                <% if user_signed_in? && current_user.id == User.find(comment.user_id).id  %>
                <h3 class="panel-title-right"><%= link_to '', comment_path(question_id: @question.id, id: comment.id), class: 'fa fa-trash', method: :delete, data: { confirm: 'Are you sure?' }  %></h3>
                <% end %>
              </div>
              <div class="panel-body">
                <p class="content"><%= markdown(comment.content) %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h4 class="text-left"><%="#{@question.answers.size} Answers" %></h4>
        <% if user_signed_in? %>
          <div class="panel-title-right">
            <%= link_to 'Create Answer', new_answer_path(question_id: @question.id), class:"btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
    <% @answers.each do |answer| %>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="question-show">
            <div class="panel-votes">
              <h3>
                <%= form_for(@vote, remote: true) do |f| %>
                  <%= hidden_field_tag "vote[amount]", true %>
                  <%= hidden_field_tag "vote[votable_id]", answer.id %>
                  <%= hidden_field_tag "vote[votable_type]", "Answer" %>
                  <%= hidden_field_tag "question_id", @question.id %>
                  <% if user_signed_in? %>
                    <%= hidden_field_tag "vote[user_id]", current_user.id %>
                  <% end %>
                  <%= button_tag type: 'submit', class: "fa fa-caret-up" do %>
                  <% end %>
                <% end %>
              </h3>
              <% if (user_signed_in? && Vote.already_vote?(current_user.id, answer.id,"Answer")) %>
                <h3 class= <%= answer.votes.where(:amount => true).count - answer.votes.where(:amount => false).count >= 0 ? 'success' : 'danger'; %>><%=answer.votes.where(:amount => true).count - answer.votes.where(:amount => false).count %></h3>
              <% else %>
                <h3><%=answer.votes.where(:amount => true).count - answer.votes.where(:amount => false).count %></h3>
              <% end %>
              <h3>
                <%= form_for(@vote, remote: true) do |f| %>
                <%= hidden_field_tag "vote[amount]", false %>
                <%= hidden_field_tag "vote[votable_id]", answer.id %>
                <%= hidden_field_tag "vote[votable_type]", "Answer" %>
                <%= hidden_field_tag "question_id", @question.id %>
                <% if user_signed_in? %>
                  <%= hidden_field_tag "vote[user_id]", current_user.id %>
                <% end %>
                <%= button_tag type: 'submit', class: "fa fa-caret-down" do %>
                <% end %>
                <% end %>
              </h3>
            </div>
            <div class="question-panel">
              <div class="panel panel-default">
                <div class="comment">
                  <p><%="Answered #{time_ago_in_words(answer.created_at)}, #{User.find(answer.user_id).email.split('@')[0]}"%></p>
                  <% if user_signed_in? && current_user.id == User.find(answer.user_id).id  %>
                    <h3 class="panel-title-right"><%= link_to '', edit_answer_path(id: answer.id,question_id: @question.id), class:'fa fa-pencil-square-o' %></h3>
                    <h3 class="panel-title-right"><%= link_to '', answer_path(question_id: @question.id, id: answer.id), class:'fa fa-trash', method: :delete, data: { confirm: 'Are you sure?' }  %></h3>
                  <% end %>
                </div>
                <div class="panel-body">
                  <p class="question-content"><%= markdown(answer.content) %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <% if user_signed_in? %>
            <a class="btn btn-primary" role="button" data-toggle="collapse" href="#collapseExample<%= answer.id %>" aria-expanded="false" aria-controls="collapseExample<%= answer.id %>">Add Comment</a>
            <br><br>
            <div class="collapse" id="collapseExample<%= answer.id %>">
              <div class="well">
                <%= form_for(@comment, remote: true) do |f| %>
                <div class="form-group">
                  <%= f.text_area :content, class:"form-control" %>
                </div>
                <%= hidden_field_tag "comment[commentable_id]", answer.id %>
                <%= hidden_field_tag "comment[commentable_type]", "Answer" %>
                <%= hidden_field_tag "question_id", @question.id %>
                <%= hidden_field_tag "comment[user_id]", current_user.id %>
                <div class="actions">
                  <%= f.submit 'Comment', class: "btn btn-success" %>
                </div>
                <% end %>
              </div>
            </div>
          <% end %>
          <% answer.comments.each do |comment| %>
          <div class="panel panel-default">
            <div class="comment">
              <p><%= "Commented #{time_ago_in_words(comment.created_at)}, #{User.find(comment.user_id).email.split('@')[0]}" %></p>
              <% if user_signed_in? && current_user.id == User.find(comment.user_id).id  %>
                <h3 class="panel-title-right"><%= link_to '', comment_path(question_id: @question.id, id: comment.id), class:'fa fa-trash', method: :delete, data: { confirm: 'Are you sure?' }  %></h3>
              <% end %>
            </div>
            <div class="panel-body">
              <p class="content"><%= comment.content %></p>
            </div>
          </div>
          <% end %>
        </div>
      </div>
  <% end %>
</div>